-- alert_event clean seed
-- Scope:
-- - alert_event is derived runtime data generated by warning evaluation jobs.
-- - Clean seed baseline keeps this table empty.

BEGIN;

INSERT INTO public.alert_event (
    event_id,
    created_at,
    updated_at,
    actual_percent,
    detail_json,
    expected_percent,
    gap_percent,
    handled_note,
    severity,
    status,
    handled_by,
    indicator_id,
    rule_id,
    window_id
)
SELECT
    NULL::bigint,
    NULL::timestamp,
    NULL::timestamp,
    NULL::numeric,
    NULL::jsonb,
    NULL::numeric,
    NULL::numeric,
    NULL::varchar,
    NULL::varchar,
    NULL::varchar,
    NULL::bigint,
    NULL::bigint,
    NULL::bigint,
    NULL::bigint
WHERE FALSE;

COMMIT;
