-- workflow_task clean seed
-- Scope:
-- - Runtime workflow task tables should start empty in clean local environments.
-- - Inbox/outbox tasks are generated by the application after workflow instances are created.

BEGIN;

-- Intentionally no seed rows.

COMMIT;
