package com.sism.analytics.interfaces.rest;

import com.sism.analytics.application.ReportApplicationService;
import com.sism.analytics.domain.Report;
import com.sism.common.ApiResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * ReportController - 报告API控制器
 * 提供报告管理相关的REST API端点
 */
@RestController
@RequestMapping("/api/v1/analytics/reports")
@RequiredArgsConstructor
@Tag(name = "Analytics Reports", description = "Report management endpoints")
public class ReportController {

    private final ReportApplicationService reportApplicationService;

    // ==================== Report Endpoints ====================

    @PostMapping
    @Operation(summary = "Create a new report")
    public ResponseEntity<ApiResponse<Report>> createReport(@RequestBody CreateReportRequest request) {
        Report report = reportApplicationService.createReport(
                request.getName(),
                request.getType(),
                request.getFormat(),
                request.getGeneratedBy(),
                request.getParameters(),
                request.getDescription()
        );
        return ResponseEntity.ok(ApiResponse.success(report));
    }

    @PostMapping("/{id}/generate")
    @Operation(summary = "Generate a report")
    public ResponseEntity<ApiResponse<Report>> generateReport(
            @PathVariable Long id,
            @RequestBody GenerateReportRequest request) {
        Report report = reportApplicationService.generateReport(
                id,
                request.getFilePath(),
                request.getFileSize()
        );
        return ResponseEntity.ok(ApiResponse.success(report));
    }

    @PostMapping("/{id}/fail")
    @Operation(summary = "Mark report generation as failed")
    public ResponseEntity<ApiResponse<Report>> failReport(
            @PathVariable Long id,
            @RequestBody Map<String, String> request) {
        Report report = reportApplicationService.failReport(id, request.get("errorMessage"));
        return ResponseEntity.ok(ApiResponse.success(report));
    }

    @PutMapping("/{id}")
    @Operation(summary = "Update report information")
    public ResponseEntity<ApiResponse<Report>> updateReport(
            @PathVariable Long id,
            @RequestBody UpdateReportRequest request) {
        Report report = reportApplicationService.updateReport(
                id,
                request.getName(),
                request.getType(),
                request.getFormat(),
                request.getDescription()
        );
        return ResponseEntity.ok(ApiResponse.success(report));
    }

    @DeleteMapping("/{id}")
    @Operation(summary = "Delete a report")
    public ResponseEntity<ApiResponse<Void>> deleteReport(@PathVariable Long id) {
        reportApplicationService.deleteReport(id);
        return ResponseEntity.ok(ApiResponse.success(null));
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get report by ID")
    public ResponseEntity<ApiResponse<Report>> getReportById(@PathVariable Long id) {
        return reportApplicationService.findReportById(id)
                .map(report -> ResponseEntity.ok(ApiResponse.success(report)))
                .orElse(ResponseEntity.notFound().build());
    }

    @GetMapping("/user/{generatedBy}")
    @Operation(summary = "Get reports by generated by user")
    public ResponseEntity<ApiResponse<List<Report>>> getReportsByGeneratedBy(@PathVariable Long generatedBy) {
        List<Report> reports = reportApplicationService.findReportsByGeneratedBy(generatedBy);
        return ResponseEntity.ok(ApiResponse.success(reports));
    }

    @GetMapping("/generated")
    @Operation(summary = "Get all generated reports")
    public ResponseEntity<ApiResponse<List<Report>>> getAllGeneratedReports() {
        List<Report> reports = reportApplicationService.findAllGeneratedReports();
        return ResponseEntity.ok(ApiResponse.success(reports));
    }

    @GetMapping("/type/{type}")
    @Operation(summary = "Get reports by type")
    public ResponseEntity<ApiResponse<List<Report>>> getReportsByType(@PathVariable String type) {
        List<Report> reports = reportApplicationService.findReportsByType(type);
        return ResponseEntity.ok(ApiResponse.success(reports));
    }

    @GetMapping("/status/{status}")
    @Operation(summary = "Get reports by status")
    public ResponseEntity<ApiResponse<List<Report>>> getReportsByStatus(@PathVariable String status) {
        List<Report> reports = reportApplicationService.findReportsByStatus(status);
        return ResponseEntity.ok(ApiResponse.success(reports));
    }

    @GetMapping("/date-range")
    @Operation(summary = "Get reports by date range")
    public ResponseEntity<ApiResponse<List<Report>>> getReportsByDateRange(
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime startDate,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE_TIME) LocalDateTime endDate) {
        List<Report> reports = reportApplicationService.findReportsByDateRange(startDate, endDate);
        return ResponseEntity.ok(ApiResponse.success(reports));
    }

    @GetMapping("/search")
    @Operation(summary = "Search reports by name")
    public ResponseEntity<ApiResponse<List<Report>>> searchReportsByName(@RequestParam String name) {
        List<Report> reports = reportApplicationService.searchReportsByName(name);
        return ResponseEntity.ok(ApiResponse.success(reports));
    }

    @GetMapping("/count/user/{generatedBy}")
    @Operation(summary = "Count reports by generated by user")
    public ResponseEntity<ApiResponse<Long>> countReportsByGeneratedBy(@PathVariable Long generatedBy) {
        long count = reportApplicationService.countReportsByGeneratedBy(generatedBy);
        return ResponseEntity.ok(ApiResponse.success(count));
    }

    @GetMapping("/count/status/{status}")
    @Operation(summary = "Count reports by status")
    public ResponseEntity<ApiResponse<Long>> countReportsByStatus(@PathVariable String status) {
        long count = reportApplicationService.countReportsByStatus(status);
        return ResponseEntity.ok(ApiResponse.success(count));
    }

    // ==================== Request DTOs ====================

    @lombok.Data
    public static class CreateReportRequest {
        private String name;
        private String type;
        private String format;
        private Long generatedBy;
        private String parameters;
        private String description;
    }

    @lombok.Data
    public static class GenerateReportRequest {
        private String filePath;
        private Long fileSize;
    }

    @lombok.Data
    public static class UpdateReportRequest {
        private String name;
        private String type;
        private String format;
        private String description;
    }
}
