package com.sism.analytics.domain;

import com.sism.shared.domain.model.base.AggregateRoot;
import com.sism.shared.domain.model.base.DomainEvent;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Report - 分析报告聚合根
 * 代表一个可导出的分析报告，支持多种导出格式
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "analytics_reports")
public class Report extends AggregateRoot<Long> {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    public static final String TYPE_STRATEGIC = "STRATEGIC";
    public static final String TYPE_EXECUTION = "EXECUTION";
    public static final String TYPE_FINANCIAL = "FINANCIAL";
    public static final String TYPE_OPERATIONAL = "OPERATIONAL";
    public static final String TYPE_COMPREHENSIVE = "COMPREHENSIVE";

    public static final String STATUS_DRAFT = "DRAFT";
    public static final String STATUS_GENERATED = "GENERATED";
    public static final String STATUS_FAILED = "FAILED";

    public static final String FORMAT_PDF = "PDF";
    public static final String FORMAT_EXCEL = "EXCEL";
    public static final String FORMAT_CSV = "CSV";
    public static final String FORMAT_HTML = "HTML";

    @Column(name = "report_name", nullable = false, length = 255)
    private String name;

    @Column(name = "report_type", nullable = false, length = 50)
    private String type;

    @Column(name = "report_format", nullable = false, length = 50)
    private String format;

    @Column(name = "status", nullable = false, length = 50)
    private String status = STATUS_DRAFT;

    @Column(name = "file_path", length = 1000)
    private String filePath;

    @Column(name = "file_size")
    private Long fileSize;

    @Column(name = "generated_by")
    private Long generatedBy;

    @Column(name = "generated_at")
    private LocalDateTime generatedAt;

    @Column(name = "report_parameters", columnDefinition = "TEXT")
    private String parameters;

    @Column(name = "description", length = 1000)
    private String description;

    @Column(name = "is_deleted", nullable = false)
    private boolean deleted = false;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * 创建分析报告
     */
    public static Report create(String name, String type, String format, Long generatedBy, String parameters, String description) {
        Report report = new Report();
        if (name == null) {
            throw new IllegalArgumentException("Report name cannot be null");
        }
        report.name = name;
        if (type == null) {
            throw new IllegalArgumentException("Report type cannot be null");
        }
        report.type = type;
        if (format == null) {
            throw new IllegalArgumentException("Report format cannot be null");
        }
        report.format = format;
        if (generatedBy == null) {
            throw new IllegalArgumentException("Generated by cannot be null");
        }
        report.generatedBy = generatedBy;
        report.parameters = parameters;
        report.description = description;
        report.status = STATUS_DRAFT;
        report.createdAt = LocalDateTime.now();

        report.validate();
        return report;
    }

    /**
     * 验证报告参数
     */
    public void validate() {
        if (name.isBlank()) {
            throw new IllegalArgumentException("Report name cannot be blank");
        }
        if (name.length() > 255) {
            throw new IllegalArgumentException("Report name cannot exceed 255 characters");
        }
        if (!isValidType(type)) {
            throw new IllegalArgumentException("Invalid report type: " + type);
        }
        if (!isValidFormat(format)) {
            throw new IllegalArgumentException("Invalid report format: " + format);
        }
        if (generatedBy == null || generatedBy <= 0) {
            throw new IllegalArgumentException("Generated by must be a positive number");
        }
        if (description != null && description.length() > 1000) {
            throw new IllegalArgumentException("Description cannot exceed 1000 characters");
        }
    }

    /**
     * 生成报告
     */
    public void generate(String filePath, Long fileSize) {
        if (status.equals(STATUS_FAILED)) {
            throw new IllegalStateException("Cannot regenerate a failed report");
        }
        this.filePath = Objects.requireNonNull(filePath, "File path cannot be null");
        this.fileSize = Objects.requireNonNull(fileSize, "File size cannot be null");
        this.status = STATUS_GENERATED;
        this.generatedAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();

        addEvent(new ReportGeneratedEvent(this));
    }

    /**
     * 生成失败
     */
    public void fail() {
        this.status = STATUS_FAILED;
        this.updatedAt = LocalDateTime.now();

        addEvent(new ReportGenerationFailedEvent(this));
    }

    /**
     * 更新报告信息
     */
    public void update(String name, String type, String format, String description) {
        if (status.equals(STATUS_GENERATED)) {
            throw new IllegalStateException("Cannot update a generated report");
        }

        if (name != null && !name.isBlank()) {
            this.name = name;
        }
        if (type != null && isValidType(type)) {
            this.type = type;
        }
        if (format != null && isValidFormat(format)) {
            this.format = format;
        }
        if (description != null) {
            this.description = description;
        }
        this.updatedAt = LocalDateTime.now();

        validate();
    }

    /**
     * 删除报告
     */
    public void delete() {
        this.deleted = true;
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * 验证报告类型
     */
    private boolean isValidType(String type) {
        return TYPE_STRATEGIC.equals(type) || TYPE_EXECUTION.equals(type) ||
                TYPE_FINANCIAL.equals(type) || TYPE_OPERATIONAL.equals(type) || TYPE_COMPREHENSIVE.equals(type);
    }

    /**
     * 验证报告格式
     */
    private boolean isValidFormat(String format) {
        return FORMAT_PDF.equals(format) || FORMAT_EXCEL.equals(format) ||
                FORMAT_CSV.equals(format) || FORMAT_HTML.equals(format);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Report report = (Report) o;
        return deleted == report.deleted &&
                Objects.equals(getId(), report.getId()) &&
                Objects.equals(name, report.name) &&
                Objects.equals(type, report.type) &&
                Objects.equals(format, report.format) &&
                Objects.equals(status, report.status) &&
                Objects.equals(generatedBy, report.generatedBy);
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), name, type, format, status, generatedBy, deleted);
    }
}

/**
 * ReportGeneratedEvent - 报告生成成功事件
 */
class ReportGeneratedEvent implements DomainEvent {

    private final Report report;

    ReportGeneratedEvent(Report report) {
        this.report = report;
    }

    public Report getReport() {
        return report;
    }

    @Override
    public String getEventType() {
        return "ReportGenerated";
    }
}

/**
 * ReportGenerationFailedEvent - 报告生成失败事件
 */
class ReportGenerationFailedEvent implements DomainEvent {

    private final Report report;

    ReportGenerationFailedEvent(Report report) {
        this.report = report;
    }

    public Report getReport() {
        return report;
    }

    @Override
    public String getEventType() {
        return "ReportGenerationFailed";
    }
}
