workflow.approver.approver-role-id=2
workflow.approver.strategy-dept-head-role-id=3
workflow.approver.vice-president-role-id=4
workflow.approver.strategy-org-id=35
workflow.approver.functional-vice-president-scope-by-org.35=35
workflow.approver.functional-vice-president-scope-by-org.36=36
workflow.approver.functional-vice-president-scope-by-org.37=37
workflow.approver.functional-vice-president-scope-by-org.38=38
workflow.approver.functional-vice-president-scope-by-org.39=39
workflow.approver.functional-vice-president-scope-by-org.40=40
workflow.approver.functional-vice-president-scope-by-org.41=41
workflow.approver.functional-vice-president-scope-by-org.42=42
workflow.approver.functional-vice-president-scope-by-org.43=43
workflow.approver.functional-vice-president-scope-by-org.44=44
workflow.approver.functional-vice-president-scope-by-org.45=45
workflow.approver.functional-vice-president-scope-by-org.46=46
workflow.approver.functional-vice-president-scope-by-org.47=47
workflow.approver.functional-vice-president-scope-by-org.48=48
workflow.approver.functional-vice-president-scope-by-org.49=49
workflow.approver.functional-vice-president-scope-by-org.50=50
workflow.approver.functional-vice-president-scope-by-org.51=51
workflow.approver.functional-vice-president-scope-by-org.52=52
workflow.approver.functional-vice-president-scope-by-org.53=53
workflow.approver.functional-vice-president-scope-by-org.54=54
workflow.approver.plan-approve-permission-code=BTN_STRATEGY_TASK_DISPATCH_APPROVE
workflow.approver.plan-report-approve-permission-code=BTN_STRATEGY_TASK_REPORT_APPROVE
workflow.approver.indicator-dispatch-approve-permission-code=BTN_INDICATOR_DISPATCH_APPROVE
workflow.approver.indicator-report-approve-permission-code=BTN_INDICATOR_REPORT_APPROVE
