-- Normalize plan.status to three business states:
-- DRAFT / PENDING / DISTRIBUTED
--
-- Workflow outcomes such as REJECTED / RETURNED / WITHDRAWN belong to
-- approval tables and should not remain as plan business statuses.

UPDATE plan
SET status = CASE UPPER(TRIM(status))
    WHEN 'IN_REVIEW' THEN 'PENDING'
    WHEN 'PENDING_APPROVAL' THEN 'PENDING'
    WHEN 'PENDING_REVIEW' THEN 'PENDING'
    WHEN 'SUBMITTED' THEN 'PENDING'
    WHEN 'APPROVED' THEN 'DISTRIBUTED'
    WHEN 'ACTIVE' THEN 'DISTRIBUTED'
    WHEN 'PUBLISHED' THEN 'DISTRIBUTED'
    WHEN 'REJECTED' THEN 'DRAFT'
    WHEN 'RETURNED' THEN 'DRAFT'
    WHEN 'WITHDRAWN' THEN 'DRAFT'
    WHEN 'CANCELLED' THEN 'DRAFT'
    WHEN 'COMPLETED' THEN 'DRAFT'
    WHEN 'ARCHIVED' THEN 'DRAFT'
    ELSE 'DRAFT'
END
WHERE status IS NOT NULL;

ALTER TABLE plan
DROP CONSTRAINT IF EXISTS ck_plan_status;

ALTER TABLE plan
ADD CONSTRAINT ck_plan_status
CHECK (status IN ('DRAFT', 'PENDING', 'DISTRIBUTED'));
